/*using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace FewerEnemies
{
    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            //Your code here!
        }
    }
}
*/

using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using System;
using System.Threading.Tasks;

namespace FewerEnemies
{
    public class Program
    {
        private static Lazy<Settings> _lazySettings = null!;
        private static Settings Settings => _lazySettings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "FewerEnemies.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            int count = 0; // running change counter
            bool skip = false;

            // iterate through all leveled lists
            foreach (var list in state.LoadOrder.PriorityOrder.LeveledNpc().WinningOverrides())
            {
                try // catch & enrich exceptions
                {
                    skip = false;
                    foreach(string Name in Settings.NameBlacklist)
                    {
                        if (list.EditorID?.Contains(Name, StringComparison.OrdinalIgnoreCase) ?? true)
                            skip = true;
                    }

                    if (skip)
                        continue;

                    if (list == null || list.EditorID == null || list.Entries == null)
                        continue;

                    var copy = Settings.ApplyTo(list.DeepCopy(), out var changes, chanceNone: Settings.GetChanceNone());

                    if (changes > 0)
                    {
                        state.PatchMod.LeveledNpcs.Set(copy);
                        Console.WriteLine($"[{++count}]\tModified {changes} entr{(changes > 1 ? "ies" : "y")} in {list.EditorID}");
                    }
                }
                catch (Exception ex)
                {
                    throw RecordException.Enrich(ex, list);
                }
            }

            Console.WriteLine($"Process completed. Modified {count} records.");
        }
    }
}